<div class="wrap">
    <h1><?php echo $this->__('Nimble Payments Summary'); ?></h1>
    <p><?php echo $this->__('Since Magento you can manage all your sales, see the movements of your account, make refunds, etc.'); ?></p>
    <p><?php echo $this->__('To access the full power of Nimble Payments from Magento, you need to identify yourself and give permission to Magento to access this data.'); ?></p>
    <p class="submit">
        <a class="button button-primary" href='<?php echo $this->url; ?>'><?php echo $this->__('Authorize Magento'); ?></a>
    </p>
</div>