<?php $_code=$this->getMethodCode(); ?>
<p style="vertical-align: middle;"><img class="credit-card-logo" src="<?php echo $this->getSkinUrl('images/nimblepayments/BBVA.png')?>" alt="<?php echo $this->__('tarjetas de credito') ?>"  style="display: inline-block; margin: 5px; vertical-align: middle;" /><strong style="display: inline-block; vertical-align: middle;"><?php echo $this->__('Pay safely with your credit card through the BBVA.') ?></strong></p>
<?php $storedCards = $this->storedcards; ?>
<?php if ( ! empty($storedCards) ):  ?>
<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <select name="payment[storedcard]">
    <?php foreach ( $storedCards as $card_id => $card ): ?>
        <option <?php if ($card['default']) echo 'selected="selected"';  ?>value="<?php echo base64_encode(json_encode($storedCards[$card_id])); ?>"><?php echo $card['maskedPan'] . ', ' . $card['cardBrand']; ?></option>
    <?php endforeach; ?>
        <option value=""><?php echo Mage::helper('core')->__('New Card'); ?></option>
    </select>
</div>
<?php endif; ?>