<div class="page-title">
	<h1><?php echo $this->__("We're sorry") // tr015 ?></h1>
</div>
<p><?php echo $this->__('An unexpected error has ocurred.') // tr016 ?></p>
<?php $contactus_link = $this->__('contact us'); ?>
<?php if (Mage::getStoreConfig('contacts/contacts/enabled')):?>
	<?php $contactus_link = '<a href="'.Mage::getUrl('contacts').'" onclick="this.target=\'_blank\'">'.$contactus_link.'</a>'; ?>
<?php endif;?>
<p><?php echo $this->__('For more information, please')." ".$contactus_link."."; // tr017 ?></p>
<?php if ($this->getOrderId()):?>
	</br>
	<?php if ($this->getCanViewOrder()) :?>
	    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
	<?php else :?>
	    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
	<?php endif;?>
	<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
	    <p>
	    	<?php echo $this->__('Click').' <a href="'.$this->getPrintUrl().'" onclick="this.target=\'_blank\'">'.$this->__('here to print').'</a> '.$this->__('a copy of your order confirmation.'); // tr018 ?>
	    </p>
	<?php endif;?>
<?php endif;?>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>

