<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?><span class="changelink"> <span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="complete">
    <?php //TODO *** ?>
    <?php echo $this->getPaymentHtml() ?>
    <p class="subtitle"><strong><?php echo Mage::helper('core')->__('Card payment'); ?></strong></p>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>

